### ISSUE TITLE
Blender 2D Keymap is not loaded

### ISSUE THREAD

**Issue by aditiapratama** [Warnakala/WKS_Storyboard#1] opened 2021-09-23 10:48 UTC
Steps :
- Open Blender and choose WKS Storyboard App Template
- everything loaded fine except the keymap still using default 

Tested in Blender 2.93.5 RC

additonal warning on console
```
Warning: 'VIEW3D_MT_wks_shot' does not contain '_PT_' with prefix and suffix
Warning: property 'recursive' not found in keymap item 'OUTLINER_OT_item_activate'
Warning: property 'recursive' not found in keymap item 'OUTLINER_OT_item_activate'
Warning: property 'recursive' not found in keymap item 'OUTLINER_OT_item_activate'
Warning: property 'use_mouse_init' not found in keymap item 'VIEW3D_OT_zoom'
Warning: property 'use_mouse_init' not found in keymap item 'VIEW3D_OT_zoom'
Warning: TypeError('bpy_struct: item.attr = val: enum "DRAW_POLY" not found in (\'DRAW\', \'DRAW_STRAIGHT\', \'ERASER\')')
Warning: property 'vertex_only' not found in keymap item 'MESH_OT_bevel'
Warning: property 'vertex_only' not found in keymap item 'MESH_OT_bevel'
Warning: property 'deselect' not found in keymap item 'ARMATURE_OT_select_linked'
Warning: property 'deselect' not found in keymap item 'ARMATURE_OT_select_linked'
```

**Comment by adhihargo** [comment] 2021-09-29 03:03
Should be fixed by this commit, though I'm still looking for more appropriate method of keymap registration through application template. Warnings are caused by the original script, better addressed separately.

**Closed as completed by adhihargo** 2021-09-29 03:03 UTC
